Update init_dist
easier to use a python script as the main filter -- can then isolate the RUN commands, as intended in Dockerfile

diff --git a/init_dist b/init_dist
--- a/init_dist
+++ b/init_dist
@@ -1,7 +1,8 @@
 #!/bin/bash
-
+  
 # get Dockerfile and pull info for postBuild etc
 # to inherit from https://raw.githubusercontent.com/jgomezdans/geog_docker/master/
+
 
 here=$(pwd)
 cmddir=$(dirname $0)
@@ -14,41 +15,65 @@ rm -rf "${tmp}"
 mkdir -p "${tmp}"
 pushd "${tmp}"
 
+# carry the pythion filter with us
+cat << EOF > filter.py
+#!/usr/bin/env python
+l=[j for j in [i.split('#')[0].split() for i in open('Dockerfile','r').read().replace("fix-permissions","chown -R ${USER} ").replace('\\\\\n','').split('\n')] if len(j)];
+
+for i,m in enumerate(l):
+  if(m[0] == 'RUN'):
+    # insert this alias in case its used
+    # m[0] = 'alias fix-permissions="chown -R ${USER} " && '
+    cmd = "bash -c " + "'" + ' '.join(m[1:]) + "'"
+  elif (m[0] == 'ARG' or m[0] == 'ENV'):
+    cmd = "export " + ' '.join(m[1:])
+  elif(m[0] == 'COPY'):
+    cmd = "cp " + ' '.join(m[1:])
+  else:
+    cmd=''
+  print(cmd)
+EOF
+
+
 # base the install on this
 wget ${base}/Dockerfile
+export CONDA_DIR=$(dirname $(dirname $(which conda)))
 
-CONDA_DIR=$(conda run env | grep 'CONDA_DIR=' | cut -d '=' -f 2) 
-
-for look in CONDA_EXE CONDA_PREFIX
-do
-  # probably CONDA_DIR is not there
-  # try CONDA_EXE
-  if [ -z "$CONDA_DIR" ]
-  then
-      CONDA_DIR=$( conda run env | grep "${look}"= | cut -d '=' -f 2)
-  fi
-  if [ -z "$CONDA_DIR" ]
-  then
-      CONDA_DIR=$( env | grep "${look}"= | cut -d '=' -f 2)
-  fi
-done
-
+if [[ ! -d "$CONDA_DIR" ]]
+then
+  unset CONDA_DIR
+fi
 
 # check we have it
-if [ ! -z "$CONDA_DIR" ]
+if [ -z "$CONDA_DIR" ]
 then
       echo "${0}: ENV ERROR"
-      echo 'ERROR: Cannot find $CONDA_DIR: I have tried $CONDA_EXE and $CONDA_PREFIX'
+      echo 'ERROR: Cannot find $CONDA_DIR:'
+      echo 'which conda returns:'
+            which conda
       echo 'from both conda run env and env'
       echo '    - Check you have anacondsa or miniconda installed'
       echo '      and put the dist in CONDA_DIR'
-      exit 0
+      exit 1
 fi
 
 echo "CONDA_DIR: $CONDA_DIR"
+#${SUDO} chown -R ${USER} .
 
 # filter Dockerfile
-grep -v FROM < Dockerfile | sed s'/COPY /cp -rf /g' | sed 's/RUN //' | sed 's/ENV //' | sed 's/ARG //' > conda.recipe
+echo '#!/bin/bash' > conda.recipe
+echo "export PATH=\"${CONDA_DIR}/bin:${PATH}\""
+echo "which conda" >> conda.recipe
+echo 'alias fix-permissions="chown -R ${USER} "' >> conda.recipe
+
+# unset the env to start with
+conda_env=$(grep conda_env Dockerfile | grep ARG | cut -d '=' -f 2)
+echo "conda deactivate && conda env remove --prefix ${conda_env}" >> conda.recipe
+
+# take the enviro=nment with us
+echo "export CONDA_DIR=${CONDA_DIR}" >> conda.recipe
+python filter.py >> conda.recipe
+chmod +x conda.recipe
 
 # get this rather than try to mimic the COPY
 wget ${base}/environment.yml
@@ -56,20 +81,33 @@ wget ${base}/environment.yml
 # so as not to mess up
 mkdir -p notebooks
 wget ${base}/notebooks/00-Test_Notebook.ipynb
-mv 00-Test_Notebook.ipynb notebooks
+mv *.ipynb notebooks
 
 # set a debug break point here
-if [ -z "$DEBUG" ]
+if [ ! -z "$DEBUG" ]
 then
   pwd
-  exit
+  exit 0
 fi
-# need to pull fix-permissions in case you use it
-wget https://raw.githubusercontent.com/jupyter/docker-stacks/master/base-notebook/fix-permissions
-chmod a+rx fix-permissions
 
-$SUDO bash conda.recipe
+${SUDO} ./conda.recipe 2| tee conda.recipe.$$.log
+
+if [ $? -eq 0 ]; then
+   echo OK
+else
+   echo "${0} FAILED with code $?"
+   echo "see log in ${CWD}/conda.recipe.$$.log"
+   exit 1
+fi
+
+# so they can carry through
+grep ENV < Dockerfile | sed 's/ENV /export /' > ${HOME}/.dockenvrc
+
+grep -v dockenvrc <  ~/.bashrc > ~/.bashrc.bak
+echo 'source ~/.dockenvrc' >> ~/.bashrc.bak
+mv ~/.bashrc.bak ~/.bashrc
 
 popd
 # tidy
-rm -rf ${tmp}
+rm -rf ${tmp} ${HOME}/tmp
+
